service: nodejs-aws-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  randomNumberGenerator:
    handler: src/handler.randomNumberGenerator
